# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spider2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import urllib.request
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon

#服务器地址
baseurl = " "
#ui代码，是pyqt5自动生成的
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 199)
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #设置个图标
        MainWindow.setWindowIcon(QIcon('bitbug_favicon.ico'))
        #设置下搜索按钮
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 50, 91, 41))
        self.pushButton.setObjectName("pushButton")
        #为鼠标点击按钮绑定事件
        self.pushButton.clicked.connect(self.buttonClicked)
        self.pushButton.setStyleSheet(
            'background-color: rgb(248,248,255);border-radius: 10px; border: 1px groove gray;border-style: outset;')
        #设置搜索框
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 10, 241, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 144, 151, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #鼠标点击触发的事件
    def buttonClicked(self):
        #向服务器发送请求得到返回值
        response = urllib.request.urlopen( baseurl+urllib.parse.quote(self.lineEdit.text()))
        doi_text = response.read().decode("utf-8")
        #创建一个提示框显示查询到的doi
        msg_box = QtWidgets.QDialog()
        msg_box.setWindowTitle("doi查询结果")
        msg_box.resize(600,70)
        #显示doi的标签
        doi_label = QtWidgets.QLabel(msg_box)
        doi_label.setAlignment(Qt.AlignCenter)
        doi_label.move(10,25)
        doi_label.setText(doi_text)
        msg_box.exec_()
        # print(self.lineEdit.text())
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "search"))
        self.pushButton.setText(_translate("MainWindow", "查询doi"))
        self.label.setText(_translate("MainWindow", "     by 某举0_0"))
